import pandas as pd
import numpy as np

def create_time_series_features(df: pd.DataFrame, target_col="units_sold") -> pd.DataFrame:
    """
    Generate lag, rolling average, and calendar features for time-series forecasting.
    Expects df sorted chronologically by date.
    """
    df = df.copy()
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date').reset_index(drop=True)

    # Calendar features
    df['day_of_week'] = df['date'].dt.dayofweek
    df['month'] = df['date'].dt.month
    df['day_of_month'] = df['date'].dt.day
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)

    # Lag features
    for lag in [1, 7, 14, 28]:
        df[f'lag_{lag}'] = df[target_col].shift(lag)

    # Rolling statistics
    for window in [7, 14, 28]:
        df[f'rolling_mean_{window}'] = df[target_col].shift(1).rolling(window=window).mean()
        df[f'rolling_std_{window}'] = df[target_col].shift(1).rolling(window=window).std()

    # Fill NaN values generated by shifting with backfill/bfill or 0
    feature_cols = [c for c in df.columns if c.startswith(('lag_', 'rolling_'))]
    df[feature_cols] = df[feature_cols].bfill().fillna(0)

    return df
